server/requirements.txt, src/schedlib/commands.py
These are just a few updates I made when setting up the scheduler to run with the end to end testing system. Quick summary:
* Add missing dependency found during install
* Disable nextline's tracing in the scheduler output for slow initialization operation
* Update for latest sorunlib API change to `wait()`
=> Miscellaneous Updates

setup.py, src/schedlib/config.py, src/schedlib/core.py, src/schedlib/instrument.py, src/schedlib/policies/__init__.py, src/schedlib/policies/basic.py, src/schedlib/policies/flex.py, src/schedlib/rules.py, src/schedlib/source.py, src/schedlib/utils.py, tests/test_config.py, tests/test_core.py, tests/test_instrument.py, tests/test_policies.py, tests/test_source.py, tests/test_utils.py
- This PR adds a new policy called `flex` which allows making planet-only schedules and allow a custom merging order should conflicts occur. 
- Also added a new rule that generate fixed elevation planet scan which supports az drift.
=> more flexible policy and drift source scan

src/schedlib/instrument.py
Previous loader assumes a fixed number of lines before the actual schedule begins. Now it computes it by finding all comments in the header.
=> support more comments in toast schedule file

src/schedlib/instrument.py, src/schedlib/policies/sat.py
currently az_speed and az_accel is set per scan, but they only need to change on nightly basis, so I removed them from the scan object and add it to the policy config.
=> sat: not set az_speed and az_accel per scan

src/schedlib/instrument.py, src/schedlib/policies/sat.py, src/schedlib/rules.py, src/schedlib/source.py
for `SATPolicy`, in the `cal_targets`, in addition to the original format: `(source_name, array_query, el_bore, tagname)`, one can also pass in a boresight rotation angle in degrees: `(source_name, array_query, el_bore, boresight_rot, tagname)`. It remains backwards compatible.
=> add support for boresight rotation in source scan

src/schedlib/policies/sat.py
in sat policy, if a source is missing in the `blocks` definition but is specified in `cal_targets`, add it automatically under `blocks['calibration']`. Remains backwards compatible.
=> add source sequence in cal_targets by default

src/schedlib/policies/sat.py
Because of https://github.com/simonsobs/scheduler/issues/43 we're currently editing the output schedules by hand to remove CMB scans that happen before a beam calibration scan and we consider the beam calibration scans more important than cmb scans. So don't skip a cal scan for something we'll remove by hand afterwards.
=> don't skip calibration operations we're editing these by hand

src/schedlib/commands.py, src/schedlib/instrument.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/stages/build_op.py
I'm not totally sure I'm done with this. But a large start and what SATp1 will run this week. Things this PR does
1. Adds az_accel to blocks b/c we're doing nonsense with turnarounds
2. cmb and cal operations now check for az speed/accel state changes
3. Add an option to implement an ISO-like alternating scan speed for every cmb scan
4. Adds option to override the toast schedule boresight since it's annoyingly wrong right now
5. If `state.boresight_rot_now` is None then boresight rotation is applied
6. Add a start_time operation that just prints a wait_until the state current time.
=> Set up for ISO

src/schedlib/instrument.py, src/schedlib/policies/__init__.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py, src/schedlib/rules.py, src/schedlib/source.py, src/schedlib/thirdparty/avoidance.py
- When assessing scan Sun safety, add a bit of a buffer in azimuth to account for turn-arounds.
- Don't consider multiple az branch options for each action -- behavior is buggy.
This is not intended for merge -- just for testing / temporary use.
@kmharrington I believe this will resolve the odd Sun Avoidance conflicts (and the weird indentation #73) encountered recently, but please check it for general good behavior.
=> One fix and one work-around related to Sun Avoidance

src/schedlib/commands.py
Add in tolerance around first `run.wait_until` in each schedule. This will prevent folks from accidentally starting a schedule intended for a time more than an hour away from the intended start.
=> Add threshold to schedule start for error prevention

src/schedlib/policies/sat.py, src/schedlib/policies/satp3.py
Updated satp3 policy to start using latest scheduler.
Added commands option for uxm_relock to be consistent with old satp3 branch.
This has been tested and it is confirmed that this change does not affect other sats.
=> update satp3 policy

src/schedlib/policies/stages/build_op.py
=> build_op: rewrap az when outside specified limits

src/schedlib/policies/sat.py, src/schedlib/policies/satp3.py
This was added in sorunlib v0.1.10 [1]. The sorunlib implementation should be preferred as it also includes error handling.
[1] - https://github.com/simonsobs/sorunlib/releases/tag/v0.1.10
=> Replace `smurf.zero_biases` with sorunlib implementation

src/schedlib/policies/satp3.py
We have not been including bgmap in our det_setup because it is only necessary right after the relock, strictly speaking.
But we discussed that it would be helpful to have it in det_setup in similar way as satp1, to avoid mistake of not running bgmap after hammering the readout slot. Also because bg map takes only for a very short period of time ~ few seconds.
=> add bgmap in satp3 policy

src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py
To resolve https://github.com/simonsobs/scheduler/issues/111
Add ability to change elevation of sun parking spot. This is critical for operation in the Chilean summer with larger sun avoidance. We configure the minimum allowed elevation in each policy. Also, added more info in the error log.
This will change the sun avoidace part of schedule like this, if it is necessary to change elevation.
```
run.wait_until('2024-10-07T14:48:24+00:00')
run.acu.move_to(az=180.0, el=60.0)
run.acu.move_to(az=180.0, el=48)
run.wait_until('2024-10-07T14:53:24+00:00')
run.acu.move_to(az=180.0, el=48)
run.wait_until('2024-10-07T18:57:35.980000+00:00')
run.acu.move_to(az=111.483, el=48)
run.acu.move_to(az=111.483, el=60.0)
run.wait_until('2024-10-07T19:02:35.980000+00:00')
run.acu.move_to(az=111.483, el=60.0) …
```
=> add ability to change elevation of sun parking spot

scripts/sun_safety_checker.py, src/schedlib/quality_assurance/__init__.py, src/schedlib/quality_assurance/sun_safety_checker.py
I've made a first pass at defining a class that can parse scheduler output .py files and determine if the specified moves, at the specified times, are actually sun-safe according to `socs.agents.acu.avoidance` module, specifically the command `check_trajectory`.
I'm still working to confirm this will catch all of the `No sun-safe moves!` or `That move violates sun safety` errors that have been crashing schedules on SATps in the past couple of months. The most recent such failure is caught (schedule beginning 20240916), but at least 1 other (schedule beginning 20240903) seems to pass -- so `check_trajectory` may not be the full story.
=> Safety checker script

src/schedlib/commands.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py
This pull request aims to address #96 by removing the move command from the `sat.wrap_up` operation and treating the post-session IR as a regular block similar to cmb or source scans.  This should also address #122, by removing the 2 individual az-only or el-only move commands and making a single az/el move for all move commands.
=> Update wrap up move command and change all moves to single command

src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py, src/schedlib/rules.py
Uses and adjusts the existing `AzRange` rule to update the Az values of calibration observations if the given Az drift results in the scan going out of the specified Az bounds.
=> Add Az wrapping for calib obs if scan goes out of Az bounds

src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py
This branch uses the existing sun-safe parking function to try and find a sun-safe home position automatically if the `stow_position` dict is empty or `None`.  It will search at `az=180` and between `el=60` and `el=sun_policy['min_el']` for a stow position.  If `az_stow` and `el_stow` are given in the config, those values are used instead and no calculation is done (in case we want to override it for some reason), though we could eliminate them from the config entirely and only use the calculated ones if we wanted to.
=> Add auto finding of sun-safe home

src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py
Updates the SAT policies `from_defaults` function to address issue #117.  The cal targets remaining even after re-instantiating the policy occurs because the default parameters are only evaluated once when the class/function is defined, so all future calls refer to the same mutable list object.
=> Fix mutable cal_target list in from_defaults

src/schedlib/commands.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py
1. Changed move_to to move az and el separately. For sun-safety, order of az el motions are different depending on whether el increases or not. This was implemented before https://github.com/simonsobs/scheduler/commit/8a608119036e29163cb0ed8bdc35c30a3ff38cc2
2. Changed order of hwp-spin up and det-setup for consistency. Previously the very first det-setup was performed with hwp stopped, others are performed when hwp is spinning.
3. Deleted wrap_up because it's not necessary. https://simonsobs.slack.com/archives/CJ8M8HY7P/p1712082764375729
4. Change HWP_SPIN_DOWN. This was discussed as scheduler requirement
=> update hwp_spin_up/down time and change order of hwp spin up for satp3

src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py
To fix https://github.com/simonsobs/scheduler/issues/164.
Add new parameter `az_speed_overwrite`, which can handle `az_speed` and `az_accel` either master file or from run.yaml file in scheduler-scripts.
I will make PR in scheduler-scripts as well.
=> add az_speed_overwrite

src/schedlib/commands.py, src/schedlib/instrument.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/__init__.py, src/schedlib/policies/stages/build_op.py
Builds on #101, but decided to make a new branch and PR so as not to mess with the `yg/dev` branch too much.  This branch imports changes that were implemented into `BuildOps` from the `main` branch into `SatPolicy` to work with the new `SatPolicy` and `BuildOpsSimple` framework from the `yg/dev` branch.  Some things in `PlanMoves` also needed changing which breaks support of `BuildOps`.
These include for now:
- Splitting the cmb observations (merging again not implemented but might not be required in new framework).
- Checking to make sure blocks only start pre-block operations when sun-safe.
- Handling stow az and alt.
- Move to sun-safe position if `home_at_end` is `False`.
=> Combining dev and main

src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py
Added a check for whether CMB and calibration blocks are above the sun avoidance minimum elevation.  An assert error will be thrown if any blocks are too low.  This is added before gap blocks or moves are calculated, which should all be guaranteed to be above the minimum elevation anyway.  Block division or merging shouldn't affect things either.
Intended to address #107.
=> Add minimum elevation check for CMB and Calib blocks

src/schedlib/policies/sat.py, src/schedlib/policies/stages/build_op.py
Changes the stow command at the end to ensure the final wait command ends at `t1`.  Previously, it would end some buffer time (usually 5 minutes) before, which will likely lead to an error when the server tries to generate a schedule that is only the length of that buffer.
Also adds an assert if the number of cmb and cal observations is greater than zero to provide a more informative error message for `nextline`.
=> Updates for scheduler-server

src/schedlib/policies/lat.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py
This is mostly to make #170 work with the `scheduler-server`.  Since it takes time for the server to determine the state of the system, the current time (determined in `get_sat_state`) will be after `t0`.  This just sets the current time of an input state file to `t0` regardless of whether the state current time was larger or smaller than `t0`.  I don't think we have any reason to allow loading in future states.
An alternative would be to set the current state to `t0` in `gen_schedule` after `get_sat_state` is called and before it is saved to a state file.
=> Always set state current time to t0

src/schedlib/policies/lat.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py, src/schedlib/policies/tel.py
Reintroduces the `wrap_up` command to add `run.acu.stop_and_clear()` at the end to ensure the telescope is stopped when the next schedule is started.
This has revealed a bug that occurs when a CMB observation leads right up to the end of the schedule, which will result in the post-session being cut despite being higher priority.  Will be fixed in a later PR.
=> Add acu_stop_and_clear

src/schedlib/policies/lat.py
Changed LAT priorities to address #190.  CMB scans are now moved to lower priority than calibration or pre-session/post-session steps.  Does not address bug mentioned in #188.
=> Change LAT priorities

src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py
Adds a `brake_hwp` command to the `SAT` policies and relevant commands, which decides if `active` should be `True` or not.
=> Add hwp braking option

src/schedlib/policies/satp3.py, src/schedlib/policies/tel.py
Addresses #185.  Adds a new state variable which measures whether there are any active channels.  If none, remove the `take_noise` command for relocking.  The variable `has_active_channels` defaults to `True`.  Will need an update to the `get_sat_state` functions to use.
Also, fixed a bug where `SATp3`'s specific relock command was replaced with the default one.
=> Add check for active channels and Re-add Satp3 relock command

src/schedlib/policies/stages/build_op.py
Fixes bug reported in #199.  Duplicate CMB scans were being added because CMB blocks that were set to `None` after being merged into another were not excluded and then overlapped with a calibration scan.
Also changed the time gap between blocks (maximum time separation between blocks that can be merged) to merge to 20 minutes to reflect changes in detector setup time elsewhere.
=> Fix bug for merge assertion error

src/schedlib/policies/lat.py
Addresses #212.  Adds support for opening and closing the shutter with `open_shutter` and `close_shutter` inputs.  The `close_shutter` command replaces `home_at_end` which isn't really used anymore due to the automatic home finding and the lack of a HWP spin down command.  Note I didn't add the shutter state to the state since I thought there might be some utility to allow the scheduler to run with the shutter down, but we can add an assert or something if required.
=> Add LAT shutter commands

src/schedlib/policies/sat.py
Addresses #171.  Cal blocks now take HWP direction from nearby CMB blocks.  Starts by trying to find a CMB block that occur after, but then searches previously if no later occurring CMB blocks were found.  Raises a `ValueError` if it cannot find any CMB blocks to copy from unless `hwp_override` is `True`.  Also, added `hwp_override` to cal blocks.  This can be used when running `no_cmb=True.`
=> Cal Block HWP direction handling

src/schedlib/policies/lat.py, src/schedlib/policies/sat.py
Ok, I made a few changes to how we're doing this to make the implementation more equal to the SATs, etc. 
From an instrument perspective we have two different ways we might want to run the co-rotator, with "Locked to elevation axis" where we set the corotator to maintain boresight = 0. Or we explicitly set the corotator position. 
* Added some comments to the acu commands because I dislike that that will be the ONLY place where boresight=co-rotator
* `apply_corotator_rotation` turns off all corotator commands. This matches with `apply_boresight_rotation` for the SATs. 
* `corotator_override` affects the CMB blocks just like `boresight_override` does. 
* also moved the SAT `hwp_override` to the same place in the block generation for consistency
* `make_cal_targets` for the LAT assumes …
=> 20250418 more corotate

src/schedlib/policies/lat.py
The reference plan does not change azimuth ranges when using elevation > 90. Which is another way of saying the reference plan doesn't reflect what we'd actually need to command to the telescope to get the "boresight=180 scans." This fixes it for the current reference plan but will need updates when we get that fixed.
=> Fix elevations under 90 work around

src/schedlib/policies/sat.py
This is based on some discussions about needing to get more data on detector time constants. This streams data every time we spin the HWP up or down. We should be able to use this data to watch the HWPSS change and calculating the detector time constants.
=> Add data streaming during HWP spin up and HWP spin down

src/schedlib/policies/lat.py, src/schedlib/policies/tel.py
Undoes the change in #223 since this is now incorporated into the [2025-04-21 LAT CMB schedule](https://github.com/simonsobs/LAT-scan-schedules/blob/main/commissioning/2025-04-21T22%3A49%3A11%2B00%3A00_lat_field_schedule.txt).  Also confirmed that this schedule seems to produce a consistent number of ~60min scans after the longer blocks are divided in the same way that the SAT scan schedules are.  Finally, added some comments in the output schedule listing the expected scan duration for future debugging.
=> Update az handling for 20250421 LAT schedules

src/schedlib/policies/stages/build_op.py
This re-arranges the order of timing updates in `plan_block_operations` to prevent the post-session from being skipped.  I think this change makes sense as we want the non-causal blocks (blocks for which their priority is the current priority) to always start at being scheduled within the constraint, not the end time of the last block, which might be lower priority.
I tested with the LAT config that was run on 04/25/25 which had this problem and it successfully adds the post-session block and did not change any of the calibration scans.
=> Adjustment to fix missing end operations

src/schedlib/instrument.py, src/schedlib/policies/sat.py
We plan to merge this PR https://github.com/simonsobs/ocs-deployment-configs/pull/436 in computing maintenance on 2025/5/8 to make the hwp rotation direction to be consistent between SATs. This will affect satp1 and satp2.
We have been using hwp-pid direction, Forward and Backward, as hwp direction terminology but this is not physically consistent with SO coords convention because of differences of instruments. The PR above will make SATs to have consistent relation (+/-) 2Hz to (ccw/cw seen from sky). To avoid confusion, I changed hwp_dir terminologies to (+/-), (ccw/cw).
=> Change hwp direction terminology to avoid confusion

src/schedlib/policies/lat.py
Relaxes the exclusion radius and minimum sun-time sun-safety parameters to value that are similar to those in the ACU.  The values are kept slightly larger to avoid rounding errors.
=> Relax sun-safety parameters for LAT

src/schedlib/commands.py, src/schedlib/policies/stages/build_op.py
Adds a tolerance of 20 minutes to the wait commands that occur before pre-block operations of all scans (CMB, calibration, and wiregrid) to make sure that commands that were supposed to be run more than 20 mins in the past are not included.  This will still add a tolerance even if the pre-block operations aren't run (i.e. hwp already spinning) because of how the blocks work, but this shouldn't be a problem I think.  Does not add a tolerance to other wait commands.
=> Add tolerance to scan pre-blocks wait commands

src/schedlib/commands.py, src/schedlib/policies/lat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py
Addresses #243.  I only made this apply to the first `set_scan_params` as everything should be consistent after that.
=> Force scan params to be set at start when overriding motions

src/schedlib/instrument.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py
Enables the wiregrid time const measurements. Reverses the state hwp direction.
=> Enable wiregrid time const measurement

src/schedlib/instrument.py, src/schedlib/policies/lat.py
Updates column handling to read in ISO schedules in https://github.com/simonsobs/LAT-scan-schedules/tree/main/iso/phase2.  The schedules need one small adjustment to the final row before this can be used.
Also slight fix for uids to make them integers.
=> Add support for ISO schedule

src/schedlib/policies/satp1.py
We can get ws3 and ws5 from boresight rotation now.
=> Remove target options because we can move in boresight again

src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py
Can now specify `ignore_wafers` in the configuration file which is a list of all wafers to be excluded from being targeted.
=> Add ability to ignore wafers to SATs

src/schedlib/policies/lat.py, src/schedlib/policies/sat.py, src/schedlib/policies/tel.py
Randomizes the order of divided blocks.  There are three cases:
- Block is too short to divide, so return only that block.
- Split into two blocks, smaller block was previously appended to the end of the list - > just randomly shuffle this.
- Split into many blocks.  If remainder is large enough, divide a block to have two >= 30 min blocks at the start and end of the sequence.  Fill the rest with the 1 hour blocks. Now just randomly shuffle all of the blocks, since it doesn't matter what order we do the 1 hour ones in and the remainders will get placed at random between them.
I set the seed to be the day of `t0`, so that things are reproducible for debugging and tracking schedules over the longterm.
=> Randomize divided block order

src/schedlib/policies/lat.py
Changes the way the corotator and boresight angles are decided upon based on the findings in recent pointing observations.
When the corotator is locked, instead of forcing a particular boresight (or -roll) angle, the `scheduler` now decides on the corotator angle first based on the elevation alone, with the corotator angle being 0 degrees at elevations of 60 deg and 120 deg.  The boresight is then determined from the corotator angle now using the `boresight = -(el - 60 - corotator)` relationship for all elevations to be consistent with the definition in other parts of the SO codebase.
=> Rework corotator angle handling

src/schedlib/instrument.py, src/schedlib/policies/stages/build_op.py, src/schedlib/policies/tel.py
Fixes some inconsistencies with sun-safety.  The sun-rule at the start checks whether movement within a scan's az, alt box is sun-safe, which is a moving target on the sky when there is drift.  Therefore, when considering the move from one scan to a next, you need to calculate the drifted az at the end of that scan and use that to check the move.  This was sort of done in a previous sun-safety PR I did, but wasn't quite correct.  For this reason, the sun-safety from the sun-rule was much larger than the sun-safety from the trajectory calculation.  Previously, the trajectory sun-safety was checking both the start and end azimuths of the first block at the end time of the first block, but this should be unnecessary since this will always be sun-safety checked when moving to that block. …
=> Overhaul sun-safety

src/schedlib/policies/sat.py
We have started running into a problem where the wiregrid measurements overlap with a calibration measurement.
This fixes it by removing the wiregrid block entirely in the event of overlap with a calibration target.  The wiregrid measurements do not have a stop time, so they will always runt their full duration, so they will always overwrite portions of other blocks unless removed.
Also changes the durations to make them reflect the fact that the wiregrid measurements will always run to their full duration.
=> Fix wiregrid overlap and durations

src/schedlib/policies/lat.py
Fixes an oversight from #269 which causes a failure for elevations under 90 degrees.
=> Fix bug for elevations under 90 deg

src/schedlib/policies/stages/build_op.py, src/schedlib/rules.py
The az range rule now not only checks just the initial and drifted az at the end of the scan, but also `az + throw`, since just checking the others can result in a scan going outside the bounds if the drift is negative and the throw is positive.
=> Fix az wrapping for drift

src/schedlib/policies/sat.py
This removes some older code in the SAT policy that was a first attempt at filtering the reference plans before we had implemented the wafer reference plans.  Removing so it does not conflict with the wafer reference plan selections.
=> Remove old SAT reference plan filtering code

src/schedlib/policies/lat.py, src/schedlib/policies/sat.py, src/schedlib/policies/satp1.py, src/schedlib/policies/satp2.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py, src/schedlib/quality_assurance/sun_safety_checker.py
More reworking of sun-safety and gaps.  There was an issue with moving between some LAT scans (https://github.com/simonsobs/LAT-scan-schedules/blob/b27d9fae66a8adacd929e6d72bf18873f412a90b/iso/phase2/2025-07-23T14%3A39%3A08%2B00%3A00_phase2_cmb_lat_field_schedule.txt#L378-L379).  This occurs when one scan runs directly into another so the gap duration is zero but it can't go from one scan to the next directly, so it finds an intermediate point.  The logic has been updated to support this.
Also, there was an inconsistency in what the `socs` avoidance tracker returned inside of `scheduler` and at the end.  This appears to be due to how often the sun tracker gets reset in the end sun safety checker.  This reduces it to reset every hour instead of 6 which solved the inconsistency.
This still …
=> Sun safety and gap changes

src/schedlib/policies/stages/build_op.py
#298 fixed issues with SATp2 but caused problems with the LAT.  This now duplicates exactly what is done in the sun-safety checker so the times should be consistent.
=> Truncate instead of rounding

src/schedlib/policies/sat.py, src/schedlib/policies/satp3.py, src/schedlib/policies/stages/build_op.py, src/schedlib/policies/tel.py, src/schedlib/thirdparty/avoidance.py
When running the same schedule with what appear to be the same versions for basically all packages (`scheduler`, `scheduler-scripts`, `SAT-scan-schedules`, `numpy`, `ocs`, `socs`, etc) there is a difference in when some scans are considered sun-safe between running on site and running on my Mac with the latter being more restrictive by a few minutes.  This reduces the refresh rate of the sun safety tracker to one hour instead of 6, which makes the site agree with my Mac.
Also makes the gap finding re-use the same sun tracker object when possible.  Won't be a big improvement for most cases, but when we run into sun-safety difficulties, this can speed that part of the code up by a large factor.
Example config where this problem occurs:
```
platform: satp3
t0: 2025-09-30T16:00:00+00:00
t1: …
```
=> Update sun tracker refresh time

src/schedlib/policies/satp3.py, src/schedlib/policies/tel.py
Updates detector setup and relock blocks according to #260.
=> Update det setup and relock blocks
