setup.py
src/schedlib/commands.py
src/schedlib/instrument.py
src/schedlib/policies/flex.py
src/schedlib/source.py

add az_drift in seq.scan

---

src/schedlib/rules.py
src/schedlib/source.py
src/schedlib/utils.py

fixed two bugs
- ctime conversion bug
- el range out of bound during interpolation issue

fix ctime bug and interp1d out of bound error

---

setup.py

- forgot about adding this back after chex is removed

add missing jax dependency

---

src/schedlib/commands.py
src/schedlib/policies/flex.py
src/schedlib/rules.py
tests/test_policies.py

change how config is being handled by flex policy such that one can more easily pass dictionary object to override the config if needed. I've also renamed the `constraint` field to `block_query` to be consistent with `array_query` since they operate the same way.

update flex constructor

---

src/schedlib/rules.py
tests/test_rules.py

add an AzRange rule to place limit on the allowed az range of scans.

Add az range rule

---

src/schedlib/core.py
src/schedlib/instrument.py
src/schedlib/policies/__init__.py
src/schedlib/policies/basic.py
src/schedlib/policies/sat.py
src/schedlib/rules.py
src/schedlib/source.py
src/schedlib/utils.py

Example script to test this:
```python
#%%
import datetime as dt
from schedlib.policies import SATPolicy
from schedlib import utils as u
geometries = {
'full': {
'left': {
'ws6': {
'center': [-10.9624, 6.46363],
'radius': 6,
},
'ws5': {
'center': [-10.9624, -6.46363],
'radius': 6,
},
},
'middle': {
'ws1': {
'center': [0, 12.634],
'radius': 6,
},
'ws0': {
'center': [0, 0], 
'radius': 6,
},
'ws4': {
'center': [0, -12.634],
'radius': 6,
},
},
'right': {
'ws2': {
'center': [10.9624, 6.46363],
'radius': 6,
},
'ws3': {
'center': [10.9624, -6.46363],
'radius': 6,
},
},
},
'bottom' : {
'ws4': {
'center': [0, -12.634],
'radius': 6,
},
'ws3': {
'center': [10.9624, -6.46363],
'radius': 6,
},
'ws5': {
'center': [-10.9624, -6.46363],
'radius': 6,
},
}
}
blocks = {
'calibration': {
'saturn': {
'type' : …
```

start to work on sat policy

---

src/schedlib/core.py
src/schedlib/policies/sat.py
src/schedlib/rules.py

found a few bugs while testing scheduler server

minor bug fixes

---

src/schedlib/source.py

fixed the bug that when rerunning a policy on a different time range, the az throw is wrong. This is due to the pre-built interpolater. I think I understood the problem. I've added a safety check for this error and also a temp fix.

source: bug in az throw

---

src/schedlib/policies/sat.py

add det setup for cmb scan

---

src/schedlib/policies/sat.py

based on changes in other software

Update SAT preamble

---

src/schedlib/source.py

found a moon scan where the angle difference at the end was like 360.5 degrees and that broke the optimization.

Prevent angle difference from being over 360 deg

---

src/schedlib/rules.py

forgot to expose allow_partial in planet rule

expose allow_partial in rule

---

src/schedlib/utils.py

allow None in nested_update during config update, which does nothing.

nested_update: allow None

---

src/schedlib/policies/sat.py

add wafer_sets to satpolicy config, which can be used to specify presets of wafer sets like
```python
wafer_sets = {
'left_boresight_0': 'ws3,ws2',
'middle_boresight_0': 'ws0,ws1,ws4',
'right_boresight_0': 'ws5,ws6',
'bottom_boresight_0': 'ws1,ws2,ws6',
'left_boresight_p45': 'ws3,ws4',
'middle_boresight_p45': 'ws2,ws0,ws5',
'right_boresight_p45': 'ws1,ws6',
'bottom_boresight_p45': 'ws1,ws2,ws3',
'left_boresight_n45': 'ws1,ws2',
'middle_boresight_n45': 'ws6,ws0,ws3',
'right_boresight_n45': 'ws4,ws5',
'bottom_boresight_n45': 'ws1,ws6,ws5',
}
```
Allow `array_query` in `cal_targets` to use `wafer_sets` look up table if the query matches with the key in this dict. 
Also added a few more checkpoints for visualization.

sat policy: allow wafer_sets definition in cal_targets

---

src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/stages/build_op.py

Scan timing check as discussed today. also added some other readability edits and things

add scan timing check, hwp direction control, and readability edits

---

src/schedlib/policies/satp1.py
src/schedlib/policies/stages/build_sched.py

More small changes to make output schedules nicer to read

more readability updates, activate divider

---

src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py

let us set how often we want to rerun detector setup and change our default IV method

IV optimization

---

src/schedlib/policies/stages/build_op.py

Currently post block operations are short, so it simplifies planning logic to ask it to finish at the end of each block which has been sun checked. Otherwise it may fail sun safety and needs to be done at a different az which is an overkill for a short operation like now.

build_op: make sure post block operations finish before the end of block

---

src/schedlib/policies/sat.py

add back in trace diabling that have gotten lost

---

src/schedlib/policies/satp3.py

Add satp3 specific det_setup (https://github.com/simonsobs/scheduler/issues/63)

Satp3 det setup

---

setup.py
src/schedlib/commands.py
src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp3.py
src/schedlib/policies/stages/build_op.py

Infrastructure for passing states through files

State passing

---

src/schedlib/policies/sat.py
src/schedlib/policies/satp3.py

Make detsetup consistent between satp1 and satp3 as much as possible.
To do that, we make sat.det_setup to accept commands.
Motivation and context: https://github.com/simonsobs/scheduler/issues/85

make sat.det_setup accept commands

---

src/schedlib/source.py

Add some sources useful for calibration.

add sources

---

src/schedlib/policies/satp2.py

SATp2 has a shiny baffle right now and not an absorptive one

Update satp2 angle to the shiny baffle number

---

src/schedlib/core.py
src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py
src/schedlib/source.py

rework cal-policy and allow speed and accel per cal target

---

src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py
src/schedlib/policies/stages/build_op.py

PR for changing the timing of biasstep. This will resolve https://github.com/simonsobs/scheduler/issues/94
This is still a draft because we have one remaining issue.

Change biasstep timing

---

src/schedlib/policies/sat.py

Needing to do this for some Jupiter scans. Looks like making sure the HWP is off is just this easy! 
Will solve issue #81

Stop HWP before boresight rotations

---

src/schedlib/policies/sat.py
src/schedlib/policies/satp3.py

This might not be a permanent solution, but satp3 tested to use this last week and found it helpful for now.
Motivation and context https://github.com/simonsobs/scheduler/issues/114

add run_initialize in det_setup

---

src/schedlib/policies/sat.py
src/schedlib/quality_assurance/sun_safety_checker.py

Made a few tweaks to the sun checker and to the formatting of the commands sent to the new timing utilities to get the setup fully parse-able by the sun checker. 
@BrianJKoopman need to rebase your branch off main and then merge these changes before #119  is ready to merge into main

Update new timing utils for sun checker

---

src/schedlib/policies/stages/build_op.py

- don't go all the way to min_el, just go as far down as you need
- don't fail because you don't have 5 extra minutes to pre-move; instead just wait until it's safe and then go to next position.
This does **not** address #113.  It's digging more into the #111 stuff.
Please test.

Two sun-safe parking changes

---

src/schedlib/instrument.py
src/schedlib/policies/satp2.py

Add parsing and state updates for schedules we'd like to use

Sched parse

---

src/schedlib/quality_assurance/sun_safety_checker.py

Draft because not complete, but adding some better formatted outputs to the sun safety checker

Sun Safe Expand

---

src/schedlib/policies/satp1.py
src/schedlib/quality_assurance/sun_safety_checker.py

I just cherry-picked out what I think we're missing from my previously messed up branch.

Sun Safety Expand -- Fixed Git

---

src/schedlib/commands.py
src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py
src/schedlib/policies/stages/__init__.py
src/schedlib/policies/stages/build_op.py
src/schedlib/policies/stages/build_sched.py
src/schedlib/quality_assurance/sun_safety_checker.py

Adjustments to try and address #128.

Add elevation check and hwp spin down for move commands if elevation too low

---

src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py

I resolved conflicts on the #143 badly. This fixes it

Fix my failed conflict resolution

---

src/schedlib/policies/sat.py

Caught this while working on this branch

missed changing one of the spin down commands

---

src/schedlib/commands.py
src/schedlib/instrument.py
src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py

Branch to parse and use new columns in schedules such as `az_speed`, `az_accel`, and `uid`.

Update to handle new schedules

---

src/schedlib/policies/sat.py
src/schedlib/policies/stages/build_op.py

Updates for hacking things so we can use this with the drone.

Drone Updates

---

src/schedlib/instrument.py

Quick fix for #153.  Not the most general solution, but should work for the main cases of failure.

Fix for syntax error from master schedule

---

src/schedlib/policies/sat.py

Fix typo in HWP command when braking is disabled.

Fix no brake HWP command

---

src/schedlib/policies/lat.py
src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py
src/schedlib/policies/tel.py
src/schedlib/rules.py

source_direction can be 'rising', 'setting', or None

Allow specification of rising or setting scans

---

src/schedlib/policies/stages/build_op.py

New branch that attempts to solve sun-safety issues.  Is a cleaner version of #201, so it will supersede that one.  Changes include:
- Fully reproduce sun-safety checking from `sun_safety_checker.py` in `build_ops` for the `get_parking` and `get_safe_gaps` functions.  This is intended to ensure all gaps and moves agree with the sun-safety checking at the end.  The old sun-safety checker is still used in `plan_block_operations` since it is faster.
- Now search a broader range of gap positions and enforce a gap even if two different observations lead directly into one another if they do not pass sun-safety  (say Jupiter rising and setting).  Positions searched include az = [180, next_az, previous_az] and elevations between the minimum and maximum elevations.  It starts at the current …

Rework sun-safety and parking

---

src/schedlib/policies/lat.py

Lowers the LAT minimum elevation limit to 0 degrees.

Update LAT lower elevation limit

---

src/schedlib/policies/lat.py

Adds `clear_faults` and `stop_and_clear` before the open shutter command.

Add clear_faults and stop_and_clear before open shutter

---

src/schedlib/policies/lat.py

use helper functions to keep things more consistant

One more update

---

src/schedlib/policies/lat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py

Sets `max_el` for sun avoidance.

Update max_el for sun avoidance

---

src/schedlib/policies/lat.py
src/schedlib/policies/sat.py
src/schedlib/policies/satp1.py
src/schedlib/policies/satp2.py
src/schedlib/policies/satp3.py

Adds configuration offsets for xi, eta, and the LAT corotator angle.  All default to zero.

Add xi/eta offsets and corotator offset

---

src/schedlib/policies/satp3.py

Disables ws5 which is currently not working for SATp3.

Disable ws5 for SATp3

---

src/schedlib/policies/lat.py
src/schedlib/policies/sat.py

Update LAT shutter controls and SAT HWP spin up and down to use the new `sorunlib` commands.

Add new sorunlib commands

---

src/schedlib/policies/lat.py

Fixes the az speed parameter for elevations over 90 degrees.

Fix az speed for el >90

---

src/schedlib/policies/lat.py

Changes `remove_targets` into `remove_cmb_targets` and `remove_cal_targets` for the LAT so we can filter out sources from both reference plans.

Add option to remove specific calibration targets

---

src/schedlib/policies/stages/build_op.py

Fixes some merge problems related to sun-safety.

Sun-safety merge fixes
